### ISSUE TITLE
Installation crash virtualenvwrapper

### ISSUE THREAD

**Issue by eamanu** [donnemartin/interactive-coding-challenges#170]
When I do:

    pip install -r requeriments.txt

and install ipython[notebook]

I have this problem when I open a terminal in ubuntu and Debian.

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/virtualenvwrapper/hook_loader.py", line 16, in <module>
    from stevedore import ExtensionManager
  File "/usr/local/lib/python2.7/dist-packages/stevedore/__init__.py", line 11, in <module>
    from .extension import ExtensionManager
  File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 17, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
virtualenvwrapper.sh: There was a problem running the initialization hooks. 

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python and that PATH is
set properly.

**Comment by eamanu** [comment]
I solve this doing:

    pip install setuptools==33.1.1

**Comment by donnemartin** [comment]
Hi @eamanu, thanks for the report and update on the fix!  Perhaps we might need to update the README for Debian/Ubuntu users?
